---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alist-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alist-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alist
  template:
    metadata:
      labels:
        app: alist
    spec:
      containers:
      - name: alist
        image: xhofe/alist:latest
        ports:
        - containerPort: 5244
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        - name: UMASK
          value: "022"
        volumeMounts:
        - name: alist-local-storage
          mountPath: /etc/alist
        - name: alist-config-storage
          mountPath: /opt/alist/data
      volumes:
      - name: alist-local-storage
        hostPath:
          path: /mnt/Pool1/CloudDisk
          type: Directory
      - name: alist-config-storage
        persistentVolumeClaim:
          claimName: alist-config

---
apiVersion: v1
kind: Service
metadata:
  name: alist-loadbalancer
spec:
  selector:
    app: alist
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5244
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: alist-nodeport
spec:
  selector:
    app: alist
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5244
      nodePort: 30007
  type: NodePort
